### ISSUE TITLE
We still need to install and configure ARPACK to use model reduction?

### ISSUE THREAD

**Issue by for-heart-peace** [FabienPean/VegaFEM#1]

**Comment by FabienPean** [comment]
Hi there, yes the model reduction part of VegaFEM is dependent on ARPACK for computing eigen modes. It can be installed with [vcpkg](https://github.com/microsoft/vcpkg) like other dependencies. It could be replaced with [spectra](https://github.com/yixuan/spectra) if needed, but I haven't checked further as I kind of drifted onto other matters.
